# Generated by Django 3.1 on 2020-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
